# Generated by Django 4.2 on 2024-04-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logs",
            options={"verbose_name": "Логи", "verbose_name_plural": "Логи"},
        ),
    ]
