# Generated by Django 4.2 on 2024-04-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_message_delete_settings_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='newsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.newsletter', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания рассылки'),
        ),
    ]
