# Generated by Django 4.2 on 2024-04-11 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания рассылки')),
                ('frequency', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=10, verbose_name='Частота рассылки')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Активная'), ('done', 'Завершена')], default='created', max_length=10, verbose_name='Статус рассылки')),
                ('datetime_start_send', models.DateTimeField(verbose_name='Дата и время начала рассылки ГГГГ-ММ-ДД ЧЧ:MM')),
                ('datetime_end_send', models.DateTimeField(verbose_name='Дата и время окончания рассылки ГГГГ-ММ-ДД ЧЧ:MM')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная')),
                ('client', models.ManyToManyField(to='mail.client', verbose_name='Адресаты рассылки')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.message', verbose_name='Сообщение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'permissions': [('set_is_activated', 'Может отключать рассылку')],
            },
        ),
    ]
