# Generated by Django 4.2 on 2024-04-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_logs_newsletter_alter_newsletter_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='newsletter',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(null=True, to='mail.client', verbose_name='Адресаты рассылки'),
        ),
    ]
