# Generated by Django 4.2 on 2024-04-05 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0005_alter_newsletter_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='datetime',
            new_name='datetime_create',
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='count_send',
            field=models.IntegerField(default=None, verbose_name='Количество отправлений'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='datetime_start_send',
            field=models.DateTimeField(null=True, verbose_name='Дата и время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
