# Generated by Django 4.2 on 2024-04-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_alter_client_owner_alter_message_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='datetime_start_send',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания рассылки'), null=True, verbose_name='Дата и время начала рассылки(по умолчанию время создания)'),
        ),
    ]
