# Generated by Django 4.2 on 2024-04-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_alter_newsletter_datetime_start_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='count_send',
        ),
        migrations.AddField(
            model_name='logs',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mail.client', verbose_name='Клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='datetime_end_send',
            field=models.DateTimeField(default=None, verbose_name='Дата и время окончания рассылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.TextField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='time_last_send',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время последней попытки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='datetime_start_send',
            field=models.DateTimeField(verbose_name='Дата и время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=10, verbose_name='Частота рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Активная'), ('done', 'Завершена')], max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
